name: Run e2e tests on docker-compose

on:
  pull_request:
    paths:
      - "deploy/**"
      - "curiefense/**"
      - "e2e/**"
      - ".github/workflows/e2e-compose-tests.yml"


jobs:
  e2e-docker-compose:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        run: |
            export BASEDIR=$(git rev-parse --show-toplevel)
            export VERSION=$(git rev-parse --short=12 HEAD)

            # Deploy all services: istio, curiefense, and echoserver (test app)
            deploy/deploy-ci-compose.sh

            echo "-- Install curieconfctl --"

            python3 -m venv "$BASEDIR/venv"
            source "$BASEDIR/venv/bin/activate"
            pip install --no-cache-dir -r "$BASEDIR/e2e/requirements.txt"

            pushd "curiefense/curieconf/utils"
            pip install -e .
            popd

            pushd "curiefense/curieconf/client"
            pip install -e .
            popd

            echo "-- Run e2e tests --"
            pushd e2e
            IP=127.0.0.1
            python3 test_e2e.py --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v3/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:9200/ --luatests-path ../curiefense/curieproxy/rust/luatests
            popd

      - name: Dump compose logs
        if: ${{ failure() }}
        run: |
            # Print logs from all services for debug
            # purposes.
            pushd deploy/compose
            docker-compose logs
