name: "Pylint"
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install pylint
        run: pip install pylint
      - name: install e2e requirements
        run: pip install -r e2e/requirements.txt
      - name: install curieconf requirements
        run: pip install curiefense/curieconf/utils/setup.py; pip install curiefense/curieconf/server/setup.py; pip install curiefense/curieconf/client/setup.py
      - name: install curielogserver requirements
        run: pip install curiefense/curielogserver/setup.py
      - name: install curietasker requirements
        run: pip install curiefense/curietasker/setup.py
      - name: run pylint
        run: shopt -s globstar; pylint --disable=R,C **/*.py
