name: Run curieconf client Javascript (Jest) tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: |
          cd "$GITHUB_WORKSPACE/curiefense/ui"
          yarn

      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/curiefense/ui"
          yarn test:unit
