name: Run curieconf client Javascript (Jest) tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change directory to client
        run: cd "$GITHUB_WORKSPACE/curiefense/ui"

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test:unit
